project:
  type: book
  output-dir: docs

book:
  title: "Textbook English: A Multi-Dimensional Approach"
  subtitle: "Online Supplements"
  author: 
  - name: Elen Le Foll
    orcid: 0000-0002-5839-8010
    email: elefoll@uni-koeln.de
  original-date: 2021-11-01
  date: last-modified
  downloads: pdf
  license: "CC BY-SA"
  sidebar:
    title: Textbook English <br>(Le Foll 2024)
    tools:
      - icon: envelope
        href: mailto:elefoll@uni-koeln.de
  page-footer:
    background: light
    left: <a href="https://www.elenlefoll.eu">Elen Le Foll</a>
    center: <a href="https://benjamins.com/catalog/scl">Textbook English</a>
    right: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a>
  site-url: https://elenlefoll.github.io/TextbookMDA/
  repo-url: https://github.com/elenlefoll/TextbookMDA/
  repo-branch: main
  chapters:
    - index.qmd
    - intro.qmd
    - OpenScience.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - AppendixA.qmd
    - AppendixB.qmd
    - AppendixC.qmd
    - AppendixD.qmd
    - AppendixE.qmd
    - AppendixF.qmd
    - AppendixG.qmd
    - AppendixH.qmd
    
execute:
  message: false
  warning: false
  cache: true

bibliography: references.bib
csl: unified-style-sheet-for-linguistics.csl

lightbox: auto

format:
  html:
    theme: cosmo
    code-fold: false
    code-overflow: wrap
    code-tools: true
    code-link: true
    link-external-newwindow: true
    footnotes-hover: true
    author-meta: "Elen Le Foll"
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}

