project:
  type: book
  output-dir: docs

book:
  title: "Textbook English: A Multi-Dimensional Approach"
  subtitle: "Online Supplements"
  author: "Elen Le Foll"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - 5a_TEC_data_prep.qmd
    - summary.qmd
    - references.qmd
   
execute:
  message: false
  warning: false

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual

