---
bibliography: references.bib
engine: knitr
---

```{css}
#| echo: false
p {
  text-align: justify
}
```

# Corpus data

## Textbook English Corpus (TEC)

A detailed tabular overview of the composition of the Textbook English Corpus (TEC) together with the full bibliographic metadata is available at [doi.org/10.5281/zenodo.4922819](https://doi.org/10.5281/zenodo.4922819).

Note that, for copyright reasons, the corpus itself cannot be published. If you are interested in using the corpus for non-commercial research purposes and/or in a potential research collaboration, please get in touch with me via [e-mail](https://orcid.org/0000-0002-5839-8010).

## Reference corpora

### Spoken BNC2014

The original corpus files of the Spoken British National Corpus (BNC) 2014 [@love2017; @love2019] can be downloaded for free for research purposes from: <http://corpora.lancs.ac.uk/bnc2014/signup.php>. I used the untagged XML version.

The R script used to pre-process the untagged XML files as explained in Section 4.3.2.2 of the book can be found here: <https://github.com/elenlefoll/TextbookEnglish/blob/main/3_Data/BNCspoken_nomark-up_JackJill.R>

### Informative Texts for Teens Corpus (Info Teens)

For copyright reasons, the corpus itself cannot be made available. Details of its composition can be found in Section 4.3.2.5 of the book. If you are interested in using this corpus for non-commercial research purposes and/or in a potential research collaboration, please get in touch with me via [e-mail](https://orcid.org/0000-0002-5839-8010).

### Youth Fiction corpus

For copyright reasons, the corpus itself cannot be made available. The corresponding metadata can be found here: <https://github.com/elenlefoll/TextbookEnglish/blob/main/3_Data/3_Youth_Fiction_Index.csv>. If you are interested in using this corpus for non-commercial research purposes and/or in a potential research collaboration, please get in touch with me via [e-mail](https://orcid.org/0000-0002-5839-8010).
